# before using this config, go through readme.md to find the onnx links to download `resnet22.onnx`
arch: resnet22
checkpoint_fp: model/weights/resnet22.pth
bfm_fp: model/configs/bfm_noneck_v3.pkl
size: 120
num_params: 62
